### ISSUE TITLE
最好还是配上对应的json

### ISSUE THREAD

**Issue by bojone** [ymcui/Chinese-ELECTRA#1]
解压后发现没有json文件，而不少框架都是根据json文件来读取模型基本结构的，建议还是配上。

比如small版
```
{
  "attention_probs_dropout_prob": 0.1,
  "directionality": "bidi",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 256,
  "initializer_range": 0.02,
  "intermediate_size": 1024,
  "max_position_embeddings": 512,
  "num_attention_heads": 4,
  "num_hidden_layers": 12,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "type_vocab_size": 2,
  "vocab_size": 21128,
  "embedding_size": 128
}
```
还有，不知道为啥ckpt的命名不加上ckpt...

最后，最新版bert4keras（0.6.4）已经能加载electra了，只需要在`build_transformer_model`里边传入`model='electra'`，欢迎用bert4keras调用哈哈～

**Comment by ymcui** [comment]
谢谢提问。
1. 因为是标准模型，finetuning的时候只需要指定'model_size'为base/small即可，无需载入额外的json。
2. 命名参考了原版electra模型，所以不带'.ckpt'，可自行下载一个英文模型解压看看。
3. 欢迎keras用户使用你的工具包加载electra模型。

**Comment by bojone** [comment]
1. base/small只是一个交流用的说法，并没有什么同一的标准，已有的albert small、roberta small就不是这个标准，所以用base/small就作为一个模型的所有参数的缩写，未免有点自封在electra的范围内了，而且不添加json文件只会使得其他框架适配electra的时候更麻烦一些，有害而无利；

2. 陋习就没必要遵循了。自有tf起，几乎所有tf保存的权重都会加上ckpt，何必反而遵循electra无端的“新”写法？

**Comment by ymcui** [comment]
后续Huggingface-Transformer正式支持ELECTRA后我们也会添加相应config文件。有需要现在使用config的用户可以使用你这边提供的json。

**Comment by mrctester** [comment]
小白路过。。。pytorch转换确实需要config，楼主提的一些建议还是很中肯的，只不过diss别人命名什么的有点不太好。
