### ISSUE TITLE
自己的文本分类数据用1e-5的lr微调，才可以收敛

### ISSUE THREAD

**Issue by WEN6Lev57q4** [ymcui/Chinese-ELECTRA#10]
ELECTRA在自己的文本分类数据上微调，用1e-5的lr才能收敛,用5e-5得到的准确率只有0.12，很奇怪。但是在RoBERTa调整lr之后效果不会差这么大

**Comment by ymcui** [comment]
PT or TF？
PT版本因为没有layer_lr_decay，性能表现可能会出现一些问题。

**Comment by WEN6Lev57q4** [comment]
确实是这个问题，thx

**Comment by AOZMH** [comment]
> PT or TF？
> PT版本因为没有layer_lr_decay，性能表现可能会出现一些问题。

请问调整lr能恢复多大程度的表现呢？PT现在能否支持分层的lr调度呢？谢谢～
