### ISSUE TITLE
如何加载开源的Model，在其上再做预训练？

### ISSUE THREAD

**Issue by Byyy233** [ymcui/Chinese-ELECTRA#11]
是将模型拷贝在./data-dir/models 里嘛？

**Comment by ymcui** [comment]
未经测试。应该和正常从头训是一样的，对应目录下要有已经下载的模型文件。

**Comment by BeyoungLIN** [comment]
同遇到这个问题，谷歌官方有提供英语预训练的方法：

**Comment by BeyoungLIN** [comment]
同遇到这个问题，谷歌官方有提供英语预训练的方法，即
Setting the model-name to point to a downloaded model (e.g., --model-name electra_small if you downloaded weights to $DATA_DIR/electra_small).
但是中文electra似乎因为去掉了adam_m而无法进一步预训练？
报错信息为：Key discriminator_predictions/dense/bias/adam_m not found in checkpoint

**Comment by ZJiaBin** [comment]
请问问题解决了没呀

**Comment by BeyoungLIN** [comment]
> 请问问题解决了没呀

没有解决……
