### ISSUE TITLE
对于 readme 的错误或疑问

### ISSUE THREAD

**Issue by XieDelong** [ymcui/Chinese-ELECTRA#15]
readme中写的是：task-name：任务名称，本例中为cmrc2018。本目录中的代码已适配了以上六个中文任务，task-name分别为cmrc2018，drcd，xnli，chnsenticorp，lcqmc，bqcorpus。

但是代码里是： if task.name in ["cola", "mrpc", "mnli", "sst", "rte", "qnli", "qqp", "sts"]:

应该要将 readme 里的 xnli 改为 mnli 吧？

**Comment by ymcui** [comment]
这一部分是GLUE数据集的部分。具体task列表：https://github.com/ymcui/Chinese-ELECTRA/blob/master/finetune/task_builder.py#L73
