### ISSUE TITLE
请问预训练语料有没有格式的处理

### ISSUE THREAD

**Issue by Byyy233** [ymcui/Chinese-ELECTRA#17]
用于预训练的语料有没有做类似于Bert或Albert的格式处理，我发现处理前后产生的tfrecord的样本量差距还是挺大的

**Comment by ymcui** [comment]
语料和我们发布的其他model相同，没有做过多的前处理，仅去除了一些特殊符号。

**Comment by Byyy233** [comment]
再多问一下，原来Bert-wwm也没用到NSP任务吗？
