### ISSUE TITLE
关于ELECTRA的预训练方法

### ISSUE THREAD

**Issue by real-brilliant** [ymcui/Chinese-ELECTRA#19]
ELECTRA由生成器+判决器构成，生成器负责把[MASK]替换成实际tokens，判决器负责区分替换结果是否和实际data中相同

但是，论文提及：
1.  >Typically k = [0.15n], i.e., 15% of the tokens are masked out
2. > if the generator happens to generate the correct token, that token is considered “real” instead of “fake

也就是说，只有 `(1 - generator_inference_acc) * 0.15`的token会被预测成fake，训练到后期就是一个极度不均衡的二分类问题（对于判决器而言），为什么判决器不会受到影响呢？

**Comment by ymcui** [comment]
建议前往[ELECTRA官方](https://github.com/google-research/electra)进行提问。

**Comment by pleomax0730** [comment]
> ELECTRA由生成器+判决器构成，生成器负责把[MASK]替换成实际tokens，判决器负责区分替换结果是否和实际data中相同
> 
> 但是，论文提及：
> 
> 1. > Typically k = [0.15n], i.e., 15% of the tokens are masked out
> 2. > if the generator happens to generate the correct token, that token is considered “real” instead of “fake
> 
> 也就是说，只有 `(1 - generator_inference_acc) * 0.15`的token会被预测成fake，训练到后期就是一个极度不均衡的二分类问题（对于判决器而言），为什么判决器不会受到影响呢？

可能如同 BERT 論問內提及的，當 mask token 比例提高了，效能反而會下降。

**Comment by real-brilliant** [comment]
> > ELECTRA由生成器+判决器构成，生成器负责把[MASK]替换成实际tokens，判决器负责区分替换结果是否和实际data中相同
> > 但是，论文提及：
> > 
> > 1. > Typically k = [0.15n], i.e., 15% of the tokens are masked out
> > 2. > if the generator happens to generate the correct token, that token is considered “real” instead of “fake
> > 
> > 也就是说，只有 `(1 - generator_inference_acc) * 0.15`的token会被预测成fake，训练到后期就是一个极度不均衡的二分类问题（对于判决器而言），为什么判决器不会受到影响呢？
> 
> @real-brilliant
> 可能如同 BERT 論問內提及的，當 mask token 比例提高了，效能反而會下降。

@pleomax0730 
我的理解是，提高MASK RATE会提高预测难度&BERT/生成器的学习难度，导致收敛时MLM任务的ACC下降；但是ELECTRA中真正要使用的是判决器，适当降低生成器的MLM ACC反而会有助于判决器进行学习（参考使用对抗学习loss/生成器size较大时，判决器性能下降的问题）。
作者在训练ELECTRA-LARGE时也的确将MASK RATE提高到了25%，不过此举对最终判决器起到了positive/negative的影响，我印象中论文没有提及。
以下是咨询作者Kevin时，作者关于此问题的回复，仅供参考

> > Good question! Yes, the discriminator task is quite imbalanced, but neural nets are pretty good at fitting highly imbalanced data. One note is that while the generator's inference accuracy is ~75%, we sample from the generator instead of taking the argmax prediction and the accuracy with sampling is around 60%. 

> >One way of thinking about why the model still works well is by comparing it with BERT. BERT learns to score the correct token highly for 15% of positions. ELECTRA learns to score the correct token highly for (1 - 0.85 - 0.15*0.6) = 94% of positions and give the other 6% of tokens low scores. So I think ELECTRA is still receiving plenty of training signal despite the imbalanced data. However, I think it probably would help performance a bit to increase the mask percentage to even-out the class imbalance; we actually did this for the ELECTRA-Large model, using a higher mask percent of 25%.

**Comment by pleomax0730** [comment]
> > > ELECTRA由生成器+判决器构成，生成器负责把[MASK]替换成实际tokens，判决器负责区分替换结果是否和实际data中相同
> > > 但是，论文提及：
> > > 
> > > 1. > Typically k = [0.15n], i.e., 15% of the tokens are masked out
> > > 2. > if the generator happens to generate the correct token, that token is considered “real” instead of “fake
> > > 
> > > 也就是说，只有 `(1 - generator_inference_acc) * 0.15`的token会被预测成fake，训练到后期就是一个极度不均衡的二分类问题（对于判决器而言），为什么判决器不会受到影响呢？
> > 
> > 
> > @real-brilliant
> > 可能如同 BERT 論問內提及的，當 mask token 比例提高了，效能反而會下降。
> 
> @pleomax0730
> 我的理解是，提高MASK RATE会提高预测难度&BERT/生成器的学习难度，导致收敛时MLM任务的ACC下降；但是ELECTRA中真正要使用的是判决器，适当降低生成器的MLM ACC反而会有助于判决器进行学习（参考使用对抗学习loss/生成器size较大时，判决器性能下降的问题）。
> 作者在训练ELECTRA-LARGE时也的确将MASK RATE提高到了25%，不过此举对最终判决器起到了positive/negative的影响，我印象中论文没有提及。
> 以下是咨询作者Kevin时，作者关于此问题的回复，仅供参考
> 
> > > Good question! Yes, the discriminator task is quite imbalanced, but neural nets are pretty good at fitting highly imbalanced data. One note is that while the generator's inference accuracy is ~75%, we sample from the generator instead of taking the argmax prediction and the accuracy with sampling is around 60%.
> 
> > > One way of thinking about why the model still works well is by comparing it with BERT. BERT learns to score the correct token highly for 15% of positions. ELECTRA learns to score the correct token highly for (1 - 0.85 - 0.15*0.6) = 94% of positions and give the other 6% of tokens low scores. So I think ELECTRA is still receiving plenty of training signal despite the imbalanced data. However, I think it probably would help performance a bit to increase the mask percentage to even-out the class imbalance; we actually did this for the ELECTRA-Large model, using a higher mask percent of 25%.

@real-brilliant
不太理解作者這段話
BERT learns to score the correct token highly for 15% of positions. ELECTRA learns to score the correct token highly for (1 - 0.85 - 0.15*0.6) = 94% of positions and give the other 6% of tokens low scores.

**Comment by real-brilliant** [comment]
@pleomax0730 
我是这么理解的，BERT仅基于15%的token进行参数迭代；

在ELECTRA中，基于生成器的预测结果，判决器接收到的输入数据的数据分布是：positive samples占比为0.85-0.94，相应地negative samples占比为0.15-0.06；
虽然是个极度不平衡的二分类问题，但相比BERT，ELECTRA有极高的数据利用率（即100%）以及极大的pretrain数据量，因此可以摆脱由于数据不平衡导致的模型过拟合问题，作者在论文中对于任务不匹配/数据利用率上带来的GLUE提升也做了对比测试，结果显示ELECTRA的性能提高相当大一部分程度上是因为提高了数据利用率
