### ISSUE TITLE
请问ELECTRA预训练会有loss降到一定程度反弹的现象嘛？MLM与disc_loss最低可以降到多少呢

### ISSUE THREAD

**Issue by Byyy233** [ymcui/Chinese-ELECTRA#21]

**Comment by ymcui** [comment]
1. 没发现明显反弹迹象
2. TensorBoard打印出来最低loss在8左右。

**Comment by Byyy233** [comment]
> 1. 没发现明显反弹迹象
> 2. TensorBoard打印出来最低loss在8左右。

loss在8左右 mlm应该是2.x 感谢您的解答
