### ISSUE TITLE
small模型预训练参数

### ISSUE THREAD

**Issue by luckper** [ymcui/Chinese-ELECTRA#22]
你好，我进行了small模型预训练，然后模型大小跟提供的不太一样，然后调用出现权重形状不兼容的错误，想问下预训练的参数这些，是多少？

**Comment by ymcui** [comment]
你好，small的config如下：
discriminator:
```json
{
  "attention_probs_dropout_prob": 0.1,
  "directionality": "bidi",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 256,
  "initializer_range": 0.02,
  "intermediate_size": 1024,
  "max_position_embeddings": 512,
  "num_attention_heads": 4,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 21128,
  "embedding_size": 128
}
```

generator:
```json
{
  "attention_probs_dropout_prob": 0.1,
  "directionality": "bidi",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 64,
  "initializer_range": 0.02,
  "intermediate_size": 256,
  "max_position_embeddings": 512,
  "num_attention_heads": 1,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 21128,
  "embedding_size": 128
}
```

**Comment by luckper** [comment]
我调用提供的electra_small模型，下游任务是可以运行的，small模型大小是49.53M
然后我用自己的语料进行run_pretraining，--hparams参数的json如下：
{
  "debug": true,
  "model_size": "small",
  "electra_objective": false,
  "num_train_steps": 1000,
  "vocab_size": 21128,
  "learning_rate": 5e-4,
  "vocab_file": "./vocab/vocab.txt",
  "pretrain_tfrecords": "./result/pretrain_data.tfrecord-0-of-1",
  "train_batch_size": 128,
  "generator_hidden_size": 1,
  "model_hparam_overrides": {
	"hidden_size": 256,
	"num_hidden_layers": 12}
  }
然后pretrain出来的模型大小为40.98M，下游调用就出现了：ValueError: Layer weight shape (128, 256) not compatible with provided weight shape (128, 144)
所以就想问下run_pretraining.py, --hparams里的参数怎么设置的？
非常感谢解答！！！！！

**Comment by ymcui** [comment]
从报错来看，有一个权重的维度是144，这个数比较奇怪。
我们训练small模型的hparam如下，并没有改动模型本身的维度信息：
```json
{
"pretrain_tfrecords":"./data/pretrain_data.tfrecord*",
"vocab_file":"./data/vocab.txt",
"model_dir":"./models/small",
"vocab_size": 21128,
"max_seq_length": 512,
"model_size": "small",
"num_train_steps": 1000000,
"save_checkpoints_steps": 10000,
"train_batch_size": 1024,
"eval_batch_size": 128,
}
```

建议你打印一下是哪一个权重的维度没有匹配上。

**Comment by luckper** [comment]
嗯嗯，应该是electra/embeddings_project/bias 这层权重没对应上。
而且我采用你发的small模型的hparam，发现模型大小model.ckpt.data大小有149M，只是把num_train_steps和train_batch_size调小了点

**Comment by luckper** [comment]
hello，之前144问题发现了，是我将debug设为true，然后hidde_size为144
运行run_pretraining.py生成的small模型文件，大小约为141M，然后接下游任务调用没有问题。
提供的small模型大小是49.53M，跟我预训练出来的small模型，采用同样的json文件接下游调用，都没有问题，且生成的模型文件大小一样，觉得很奇怪

**Comment by ymcui** [comment]
因为我们把adam_v和adam_m删掉了，这样可以让模型缩减为原来的约1/3。

**Comment by luckper** [comment]
hello，你好，想问下adam_v和adam_m是怎么处理删掉的？因为我看optimization的apply_gradients里，bert、albert都是采用adam_v和adam_m
辛苦解答，万分感谢！

**Comment by ymcui** [comment]
优化器改为SGD，重新load一下就会保存一套去掉adam_*的权重了。

**Comment by ymcui** [comment]
如没有其他问题就先关闭了。
