### ISSUE TITLE
可以提供一下预训练的配置和耗时信息吗？

### ISSUE THREAD

**Issue by HuaYZhao** [ymcui/Chinese-ELECTRA#23]
我在chinese_electra_base的基础上，在自己的语料上继续预训练。发现训练速度特别慢。一个多小时200步。
我用的设备是tpu-v3。希望可以得到你们预训练的经验分享。谢谢

**Comment by HuaYZhao** [comment]
使用的batch_size也是256

**Comment by ymcui** [comment]
简单计算了一下，大约是7min/1k-steps，batch为256，最大长度512。

**Comment by HuaYZhao** [comment]
运行设备可以说一下吗？

**Comment by ymcui** [comment]
TPUv3

**Comment by HuaYZhao** [comment]
好的，谢谢。我查一下问题

**Comment by HuaYZhao** [comment]
我发现了导致这个问题的原因。electra默认会将预训练数据生成1000个tfrecord文件，而我的数据量又比较少，只有数万文本行，再加上设置了256的batch_size,就导致了性能瓶颈。
解决这个问题只需要修改生成的tfrecord文件个数即可

**Comment by ymcui** [comment]
@HuaYZhao 感谢反馈，你的相关经验会帮助到其他遇到同样问题的同学
