### ISSUE TITLE
关于Loss计算的问题

### ISSUE THREAD

**Issue by RookieZB** [ymcui/Chinese-ELECTRA#24]
您好，下游任务损失函数是加和（reduce_sum）计算，而非对Batch求均值（reduce_mean），感觉对部分非Adam优化器的结果会产生影响。想请教一下，这一细节是有意为之还是不会影响模型效果？此外非常感谢共享中文预训练模型。

**Comment by ymcui** [comment]
https://github.com/ymcui/Chinese-ELECTRA/blob/master/run_finetuning.py#L72
看似是对不同task之间求和（可能是为了做multi-task learning）。没有指定axis的时候实际上是对所有任务（外层）和batch（内层）都求和了。具体原作者为什么这么设置我也不是很清楚，你可以去ELECTRA官方目录进行提问。由于BERT一类模型基本都是基于Adam或者相关变种进行训练的，所以可能也不会有太大影响。

将L72改为reduce_mean后，以ELECTRA-small-ex模型在ChnSentiCorp上的效果为例，基本没有统计显著性变化（5次运行最大值）。
```
reduce_sum: 92.58 / 93.58
reduce_mean: 92.50 / 93.25
```

供参考。

**Comment by RookieZB** [comment]
> https://github.com/ymcui/Chinese-ELECTRA/blob/master/run_finetuning.py#L72
> 看似是对不同task之间求和（可能是为了做multi-task learning）。没有指定axis的时候实际上是对所有任务（外层）和batch（内层）都求和了。具体原作者为什么这么设置我也不是很清楚，你可以去ELECTRA官方目录进行提问。由于BERT一类模型基本都是基于Adam或者相关变种进行训练的，所以可能也不会有太大影响。
> 将L72改为reduce_mean后，以ELECTRA-small-ex模型在ChnSentiCorp上的效果为例，基本没有统计显著性变化（5次运行最大值）。
> reduce_sum: 92.58 / 93.58
> reduce_mean: 92.50 / 93.25
> 
> 供参考。

好的，非常感谢！

**Comment by RookieZB** [comment]
您好，冒昧再请教，能否提供Base和Large的Generator参数config，或者明确一下这两者的head数量也行。谢谢！

**Comment by ymcui** [comment]
https://huggingface.co/hfl
所有的文件都在上面的链接中。点击你想了解的模型之后，在新页面选择`See raw config file`

**Comment by RookieZB** [comment]
> https://huggingface.co/hfl
> 所有的文件都在上面的链接中。点击你想了解的模型之后，在新页面选择See raw config file

原来如此，非常感谢！
