### ISSUE TITLE
我在finetune CMRC 2018时发现预处理得到的数据不及预期

### ISSUE THREAD

**Issue by HuaYZhao** [ymcui/Chinese-ELECTRA#25]
我看了finetune/qa/qa_tasks.py中的代码，似乎与原版的electra一模一样。
官方的代码针对squad2.0的预处理是英文的。英文的预处理可以适配中文的qa数据吗？
我们在运行该仓库的代码finetune CMRC数据时。得到的example大致如下

> {'task_name': 'cmrc2018', 'eid': 0, 'qas_id': 'TRAIN_186_QUERY_0', 'qid': None, 'question_text': '范廷颂是什么时候被任为主教的？', 'doc_tokens': ['范廷颂枢机（，），圣名保禄·若瑟（），是越南罗马天主教枢机。1963年被任为主教；1990年被擢升为天主教河内总教区宗座署理；1994年被擢升为总主教，同年年底被擢升为枢机；2009年2月离世。范廷颂于1919年6月15日在越南宁平省天主教发艳教区出生；童年时接受良好教育后，被一位越南神父带到河内继续其学业。范廷颂于1940年在河内大修道院完成神学学业。范廷颂于1949年6月6日在河内的主教座堂晋铎；及后被派到圣女小德兰孤儿院服务。1950年代，范廷颂在河内堂区创建移民接待中心以收容到河内避战的难民。1954年，法越战争结束，越南民主共和国建都河内，当时很多天主教神职人员逃至越南的南方，但范廷颂仍然留在河内。翌年管理圣若望小修院；惟在1960年因捍卫修院的自由、自治及拒绝政府在修院设政治课的要求而被捕。1963年4月5日，教宗任命范廷颂为天主教北宁教区主教，同年8月15日就任；其牧铭为「我信天主的爱」。由于范廷颂被越南政府软禁差不多30年，因此他无法到所属堂区进行牧灵工作而专注研读等工作。范廷颂除了面对战争、贫困、被当局迫害天主教会等问题外，也秘密恢复修院、创建女修会团体等。1990年，教宗若望保禄二世在同年6月18日擢升范廷颂为天主教河内总教区宗座署理以填补该教区总主教的空缺。1994年3月23日，范廷颂被教宗若望保禄二世擢升为天主教河内总教区总主教并兼天主教谅山教区宗座署理；同年11月26日，若望保禄二世擢升范廷颂为枢机。范廷颂在1995年至2001年期间出任天主教越南主教团主席。2003年4月26日，教宗若望保禄二世任命天主教谅山教区兼天主教高平教区吴光杰主教为天主教河内总教区署理主教；及至2005年2月19日，范廷颂因获批辞去总主教职务而荣休；吴光杰同日真除天主教河内总教区总主教职务。范廷颂于2009年2月22日清晨在河内离世，享年89岁；其葬礼于同月26日上午在天主教河内总教区总主教座堂举行。'], 'orig_answer_text': '1963年', 'start_position': 0, 'end_position': 0, 'is_impossible': False}

该预处理似乎无法正确的进行token的切分以及start、end位置的查找。

**Comment by ymcui** [comment]
你贴的这个阶段还没有调用tokenizer。😅
https://github.com/ymcui/Chinese-ELECTRA/blob/master/finetune/qa/qa_tasks.py#L272

**Comment by timbereye** [comment]
这里对中文的处理可能有点问题，上面得到的example里答案的位置信息实际上是丢失的。
调用tokenizer之后通过_improve_answer_span得到了位置信息（https://github.com/ymcui/Chinese-ELECTRA/blob/master/finetune/qa/qa_tasks.py#L288-L290），但是这里的位置只能是答案在段落中首次出现的位置，也就是说如果段落中出现了多次答案，这里得到的位置很可能与标注不一致。
我修复了该问题后，在electra-small上跑了CMRC2018和DRCD数据集，得到的结果好于报告中的结果，这里使用默认参数，只跑了一次。
CMRC2018 DEV:
原始报告：63.4 (62.9) / 80.8 (80.2)
实验结果：{"AVERAGE": "72.868", "F1": "82.021", "EM": "63.715", "TOTAL": 3219, "SKIP": 0, "FILE": "gs://squad_c/CEData/models/electra_small/results/cmrc2018_qa/cmrc2018_dev_preds.json"}
DRCD DEV:
原始报告：79.8 (79.4) / 86.7 (86.4)
试验结果：{"AVERAGE": "83.449", "F1": "86.649", "EM": "80.250", "TOTAL": 3524, "SKIP": 0, "FILE": "gs://squad_c/CEData/models/electra_small/results/drcd_qa/drcd_dev_preds.json"}
