### ISSUE TITLE
huggingface的tokenizer问题

### ISSUE THREAD

**Issue by vincehxb** [ymcui/Chinese-ELECTRA#27]
首先感谢作者所做的工作，我在使用过程中有两个疑问
1. 请问ELECTRA可以使用huggingface的bert-tokenizer吗？词表完全相同是否能用相同的tokenizer?
2. 请问Chinese-ELECTRA的预训练语料有多大呢?

**Comment by ymcui** [comment]
你好，
1. Tokenizer使用的是WordPiece，也是ELECTRA官方模型默认的tokenizer。原则上BERT/ELECTRA可以使用同样的tokenizer（未经过测试比对）。但还是建议在使用transformers工具包的时候调用模型对应的tokenizer。
2. 预训练语料的纯文本格式大约占用10G+，按字计算的话大约5.4B。
