### ISSUE TITLE
想加载已有模型进一步预训练时缺少adam应该怎么办呢？

### ISSUE THREAD

**Issue by BeyoungLIN** [ymcui/Chinese-ELECTRA#28]
谷歌原repo提到对已有模型经一部预训练的方法是将路径改到已有模型上继续运行run_pretraining.py，即
Setting the model-name to point to a downloaded model (e.g., --model-name electra_small if you downloaded weights to $DATA_DIR/electra_small).
但使用中文electra时似乎因为去掉了adam_m而无法进一步预训练
报错信息为：Key discriminator_predictions/dense/bias/adam_m not found in checkpoint

**Comment by ymcui** [comment]
暂无法提供完整版权重。
