### ISSUE TITLE
自己的文本多分类任务，训练时展示没有acc，只有loss?

### ISSUE THREAD

**Issue by waywaywayw** [ymcui/Chinese-ELECTRA#30]
![image](https://user-images.githubusercontent.com/26199465/85004098-bdbae700-b189-11ea-9d94-1e5832ef7a48.png)
只有loss 没有acc 作为参考

**Comment by ymcui** [comment]
是的，原版代码既如此。

**Comment by waywaywayw** [comment]
那如果想看acc，可以指导下 改哪些地方可以实现吗。

**Comment by ymcui** [comment]
1. 如果是想实时看到开发集上的acc的话比较麻烦，常用方法是多存一些ckpt，然后在训练结束后一并进行测试（参考ALBERT原版代码的做法）。
2. 如果是train上的acc，需要向ETAHook传入计算出来的acc（参考loss的做法），并且修改ETAHook的传入参数（util/training_utils.py）
`https://github.com/ymcui/Chinese-ELECTRA/blob/master/run_finetuning.py#L126`

**Comment by waywaywayw** [comment]
好的，谢谢
那退一步的话 只想看验证集的acc 有比较方便的做法吗

**Comment by ymcui** [comment]
常见的做法就是上面①里所说的了。其他的方法暂不清楚。

**Comment by waywaywayw** [comment]
好的，谢谢了
