### ISSUE TITLE
IOError in tf.io.TFRecordWriter(output_file) 

### ISSUE THREAD

**Issue by miraclzhou** [ymcui/Chinese-ELECTRA#31]
there is a bug in finetune/preprocessing.py  
def _serialize_dataset(self, tasks, is_training, split):

utils.mkdir(tfrecords_path.rsplit("/", 1)[0])
this code used "/" as split flag to split out_file path ,if this code running in widows ,it might make the filename as directory ,then it will make IOError in method "def serialize_examples(self, examples, is_training, output_file, batch_size):"  -->with tf.io.TFRecordWriter(output_file) as writer: 
 PLS use  "utils.mkdir(tfrecords_path.rsplit(os.sep,1)[0])"  insteadof "utils.mkdir(tfrecords_path.rsplit("/", 1)[0])"

**Comment by ymcui** [comment]
It seems not to be a bug but an error in your `filename`.
Could you paste your command line for running this script?

**Comment by miraclzhou** [comment]
python run_finetuning.py --data-dir e:\py_work\electra\train_data --model-name chinese_electra_base_L-12_H-768_A-12  --hparams hparam.json

**Comment by ymcui** [comment]
It seems to be an error by windows, while this code (and ELECTRA official code) is only tested under linux system. If you are interested in fixing this issue, please go to ELECTRA official (https://github.com/google-research/electra) and submit a PR.
