### ISSUE TITLE
CMRC 2018训练集和开发集输入数据格式对么？

### ISSUE THREAD

**Issue by nonva** [ymcui/Chinese-ELECTRA#33]
代码中
input_data = json.load(f)["data"]
for entry in input_data:
  for paragraph in entry["paragraphs"]

train.json 不是这个格式，直接跑不起来？

**Comment by ymcui** [comment]
有两种格式的CMRC 2018数据（原始格式/SQuAD格式）：
https://worksheets.codalab.org/worksheets/0x92a80d2fab4b4f79a2b4064f7ddca9ce
