### ISSUE TITLE
关于预训练，步骤可以写的详细一点吗？

### ISSUE THREAD

**Issue by Hanlard** [ymcui/Chinese-ELECTRA#37]
比如 ：
1）数据格式 
2）运行代码步骤

多谢！

**Comment by ymcui** [comment]
请勿重复开帖，你在https://github.com/ymcui/Chinese-ELECTRA/issues/34 这里已经提问过了。
这属于通用ELECTRA的问题，建议你去ELECTRA官方目录进行提问。
