### ISSUE TITLE
ELECTRA-small, Chinese 权重丢了5个？

### ISSUE THREAD

**Issue by qgzang** [ymcui/Chinese-ELECTRA#4]
提供开源模型的老师，您好，我通过讯飞云下载的模型， 解析ELECTRA-small模型发现有五个权重找不到。
error electra/encoder/layer_9/intermediate/dense/kernel
error electra/encoder/layer_9/output/LayerNorm/beta
error electra/encoder/layer_9/output/LayerNorm/gamma
error electra/encoder/layer_9/output/dense/bias
error electra/encoder/layer_9/output/dense/kernel

请检查是否存在该问题，十分感谢。

换了个源下载是ok的，抱歉

**Comment by qgzang** [comment]
fixed

**Comment by ymcui** [comment]
你好，请问是我们提供的链接有误吗？

**Comment by qgzang** [comment]
> 你好，请问是我们提供的链接有误吗？

可能是网络问题，下载的压缩包不完整。

**Comment by ymcui** [comment]
好的
