### ISSUE TITLE
关于并行

### ISSUE THREAD

**Issue by Hanlard** [ymcui/Chinese-ELECTRA#40]
您好，我在8个2080Ti上进行预训练，只有一个GPU显存几乎占满，另外7个都是只是用100M左右，加大batch_size就出现OOM问题了，请问代码中，有设置GPU使用的超参数吗，看了一遍没有找到。

**Comment by ymcui** [comment]
你好，
1. 这个属于通用ELECTRA问题，建议你去官方ELECTRA目录进行提问；
2. 代码方面我们仅做了一些适配，并未改动太多；
3. 本目录中的所有实验均运行于TPU上。

我搜索了一下官方ELECTRA目录，目前的代码好像是不支持multi-gpu的，相关讨论参考：https://github.com/google-research/electra/issues/9

**Comment by Hanlard** [comment]
> 你好，
> 
> 1. 这个属于通用ELECTRA问题，建议你去官方ELECTRA目录进行提问；
> 2. 代码方面我们仅做了一些适配，并未改动太多；
> 3. 本目录中的所有实验均运行于TPU上。
> 
> 我搜索了一下官方ELECTRA目录，目前的代码好像是不支持multi-gpu的，相关讨论参考：[google-research/electra#9](https://github.com/google-research/electra/issues/9)

明白，我自己改一下好了，谢谢

**Comment by ymcui** [comment]
由于没有进一步讨论，本issue关闭。如有需要可随时reopen。

**Comment by ZJiaBin** [comment]
> > 你好，
> > 
> > 1. 这个属于通用ELECTRA问题，建议你去官方ELECTRA目录进行提问；
> > 2. 代码方面我们仅做了一些适配，并未改动太多；
> > 3. 本目录中的所有实验均运行于TPU上。
> > 
> > 我搜索了一下官方ELECTRA目录，目前的代码好像是不支持multi-gpu的，相关讨论参考：[google-research/electra#9](https://github.com/google-research/electra/issues/9)
> 
> 明白，我自己改一下好了，谢谢

请问是改动了哪里呢，我也遇到了这个问题~
