### ISSUE TITLE
预训练数据量

### ISSUE THREAD

**Issue by frostjsy** [ymcui/Chinese-ELECTRA#41]
大神，我想问下，electra-small, electra-large预训练的训练数据大概是多少？

**Comment by ymcui** [comment]
你好，纯文本数据大约10G。
与https://github.com/ymcui/Chinese-BERT-wwm目录中的`-ext`类型模型使用的数据是一致的。

**Comment by ymcui** [comment]
由于没有进一步讨论，本issue关闭。如有需要可随时reopen。
