### ISSUE TITLE
how to download a tf2.0 model of electra-hongkongese-large-discriminator ??

### ISSUE THREAD

**Issue by marcusau** [ymcui/Chinese-ELECTRA#42]
Thanks for your amazing work

I would like to use  a bert4keras framework to funetine a model for ner task.   

Therefore, i would like to download a electra HK large discriminator for tf2.0 to my local machine.

Thanks

Marcus

**Comment by ymcui** [comment]
Thank you for having interests in our work.
As of now, we are not providing any ELECTRA models on HK data. 
The model (`electra-hongkongese-large-discriminator`) you mentioned in https://github.com/ymcui/Chinese-ELECTRA/pull/43 seems to a work by @toastynews .
You can download this model through https://huggingface.co/toastynews/electra-hongkongese-large-discriminator by clicking `List all files in model`.
<img width="540" alt="image" src="https://user-images.githubusercontent.com/16095339/87782025-56fe1b80-c864-11ea-8471-3763dde78b95.png">

**Comment by toastynews** [comment]
Hi @marcusau ,

The _tf_model.h5_ file is the output of converting the Pytorch model to TF2 using [this process](https://huggingface.co/transformers/model_sharing.html#make-your-model-work-on-all-frameworks).

For the discriminator, TFElectraForPreTraining was used.
For the generator, TFElectraForMaskedLM was used.

Please direct further queries to https://github.com/toastynews/electra-hongkongese
