### ISSUE TITLE
请告知params_cmrc2018.json这个文件所在之处

### ISSUE THREAD

**Issue by ChrisChaw** [ymcui/Chinese-ELECTRA#44]
您好：
       我看了这个项目的README，不太清楚params_cmrc2018.json这个文件在哪里，烦请告知，非常感谢！
                                                                                                                                                        此致敬礼！

**Comment by ymcui** [comment]
目录中并没有这个文件，README中给出了样例，你可以参考编写并保存成json文件。例如：

{
    "task_names": ["cmrc2018"],
    "max_seq_length": 512,
    "vocab_size": 21128,
    "model_size": "small",
    "do_train": true,
    "do_eval": true,
    "write_test_outputs": true,
    "num_train_epochs": 2,
    "learning_rate": 3e-4,
    "train_batch_size": 32,
    "eval_batch_size": 32,
}

**Comment by samosun** [comment]
目录中并没有这个文件，README中给出了样例，你可以参考编写并保存成json文件。例如：

{
"task_names": ["cmrc2018"],
"max_seq_length": 512,
"vocab_size": 21128,
"model_size": "small",
"do_train": true,
"do_eval": true,
"write_test_outputs": true,
"num_train_epochs": 2,
"learning_rate": 3e-4,
"train_batch_size": 32,
"eval_batch_size": 32
}
最后一个property没有逗号
