### ISSUE TITLE
询问项目入口文件与项目启动命令

### ISSUE THREAD

**Issue by ChrisChaw** [ymcui/Chinese-ELECTRA#45]
请问该项目的入口文件是哪一个？项目启动命令是什么？烦请告知，感谢！

**Comment by ymcui** [comment]
麻烦你仔细阅读一下README（https://github.com/ymcui/Chinese-ELECTRA#使用方法），fine-tuning相关的步骤都已经写上去了。同时你也可以参考ELECTRA官方的教程：https://github.com/google-research/electra
