### ISSUE TITLE
多分类任务如何修改？

### ISSUE THREAD

**Issue by Wangkaixinlove** [ymcui/Chinese-ELECTRA#5]
如果进行多分类情感分析的话，修改哪里呢？直接将CnSentiCorp任务里的["0","1"]修改为["1","2","3","4","5"]吗？

**Comment by Wangkaixinlove** [comment]
还有一个问题关于数据集的格式，必须是.json文件吗？.csv或者.tsv是否可以呢

**Comment by Wangkaixinlove** [comment]
3.我看到配置文件里面只有do_train和do_eval有没有像bert一样的do_test操作呢？最后会输出测试结果文件的那种～

**Comment by ymcui** [comment]
不好意思，才看到。

1. 对的，可以修改这里https://github.com/ymcui/Chinese-ELECTRA/blob/master/finetune/classification/classification_tasks.py#L463  ，注意把标签["0", "1"]改为你的任务中的实际的标签列表
2. 数据格式可以是任意的，比如ChnSentiCorp这个class下，读的就是tsv格式的。https://github.com/ymcui/Chinese-ELECTRA/blob/master/finetune/classification/classification_tasks.py#L467  这些API都比较易懂，建议看一下里面每个参数的含义。
3. config.write_test_outputs 这个开启之后会写入数据，可以参考https://github.com/ymcui/Chinese-ELECTRA/blob/master/run_finetuning.py#L288

**Comment by ymcui** [comment]
如有其他问题，可随时reopen。
