### ISSUE TITLE
Sentiment classification

### ISSUE THREAD

**Issue by ML-PPAP** [ymcui/Chinese-ELECTRA#52]
您好，很感谢您的分享，我想用ELECTRA-large做二分类的情感分类，该如何进行代码复现呢，目前我遇到了问题不知道怎么解决，望您指导，谢谢

**Comment by ymcui** [comment]
可参考：https://github.com/ymcui/Chinese-ELECTRA#使用方法
或ELECTRA官方：https://github.com/google-research/electra#fine-tuning

主要是根据任务修改task定义，情感二分类任务可参考ChnSentiCorp写一个class。https://github.com/ymcui/Chinese-ELECTRA/blob/master/finetune/classification/classification_tasks.py#L458

**Comment by ML-PPAP** [comment]
谢谢你的指导

**Comment by ML-PPAP** [comment]
您好，谢谢您的回复，请问一下对于evaluate我应该怎么改写呢，第一步的fine-tuning已经弄好，想通过evaluate查看结果，但是在cmrc2018_drcd_evaluate.py中的json.load(open(args.dataset_file, 'rb'))代码块出现错误->json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)，请问这个错误应该怎么改正呢，我思考的是我的dataset_dir和prediction_file文件指定错误，但是具体应该是什么，我也不知道怎么弄，望您指导

**Comment by ymcui** [comment]
cmrc2018_drcd_evaluate.py脚本是阅读理解任务CMRC 2018和DRCD用的。
普通二分类任务直接看log输出里的accuracy就行了。
即如果finetuning已经结束，且json配置文件开启了do_eval为true，就可以在log中搜索`accuracy`就能找到测试集对应的准确率了。
