### ISSUE TITLE
请问中文的预训练，mask的粒度是字符粒度，这有什么道理吗，为什么不采用词粒度呢

### ISSUE THREAD

**Issue by meteorshowers** [ymcui/Chinese-ELECTRA#53]

**Comment by menghuanlater** [comment]
词粒度还是有点大了，OOV问题会比较严重

**Comment by meteorshowers** [comment]
中文  字粒度能学出来语意相关性吗，效果是不是会有所下降？

**Comment by menghuanlater** [comment]
从语意相关性角度而言，词粒度确实要比字粒度好，但现实情况下应用的时候，由于ZipF定律的存在，大部分词几乎都没怎么出现过，特别是进行迁移学习的时候，OOV问题非常严重，而且一般用词粒度的话模型相对应的词表嵌入矩阵我们需要设置的很大，不管从存储还是性能角度而言，都有很大的缺陷，所以word_embedding方法之后，很多模型都会尝试在词嵌入基础上加上一个基于字符序列的表示。然后对于中文BERT类模型来说，由于模型大，训练语料又非常的足，其实很多时候模型可以自己学习到相关的语义表示的，否则也不会带来这么大的提升了

**Comment by meteorshowers** [comment]
感谢， 中文如果使用bpe这种分词应该是可以不oov吧，您怎么看呢

**Comment by menghuanlater** [comment]
嗯，好像字粒度的就近似等于bpe算法了，毕竟中文的词和英文的词还是有区别的
