### ISSUE TITLE
Bert service 使用 chinese-electra-base 模型，输出结果有问题

### ISSUE THREAD

**Issue by Echo0117** [ymcui/Chinese-ELECTRA#58]
环境：

PaddleHub 1.8.1
PaddlePaddle 1.8.4
paddle-gpu-serving >=0.8.2
ujson >=1.35

```
# coding: utf8
from paddlehub.serving.bert_serving import bs_client

if __name__ == "__main__":
    # 初始化bert_service客户端BSClient
    bc = bs_client.BSClient(module_name="ernie", server="127.0.0.1:8866")

    # 输入要做embedding的文本
    # 文本格式为[["文本1"]]
    input_text = [
        ["西风吹老洞庭波"]
    ]

    # BSClient.get_result()获取结果
    result = bc.get_result(input_text=input_text)

    # 打印输入文本的embedding结果
    for item in result:
        print(item)
```
在使用 bert_service_client 时，引入erine 模型的 get_result是一个数组，但是 chinese-electra-base 就只有一个值,
请问是为什么呢？然后可以让 chinese-electra-base 模型的输出结果也是一个和 erine 结果维度一样的数组吗？

![image](https://user-images.githubusercontent.com/54064209/99787109-4800e000-2b5a-11eb-8fa6-9be651ce5691.png)
![image](https://user-images.githubusercontent.com/54064209/99787122-4cc59400-2b5a-11eb-8707-4f33d119dcae.png)

**Comment by ymcui** [comment]
抱歉，paddle方面我们这边不是很清楚，因此无法提供支持。
你可以尝试加载英文原版的electra，看看是否有问题。

**Comment by Echo0117** [comment]
嗯嗯，我发现是 paddle 源码的问题，他们写漏了一段代码，我已经改过然后解决了～
谢谢你的回复～

Yiming Cui <notifications@github.com> 于2020年11月21日周六 上午9:06写道：
