### ISSUE TITLE
在下游中文ner任务中, electra各个模型学习率应该设置多大？

### ISSUE THREAD

**Issue by passion765** [ymcui/Chinese-ELECTRA#60]

**Comment by ymcui** [comment]
并没有统一的值，需要在你的数据上自行调整。通常以默认值为基准向两边适当调整以寻求最佳学习率。
small/small-ex/base/large: 5e-4 / 5e-4 / 1e-4 / 5e-5

**Comment by passion765** [comment]
> 并没有统一的值，需要在你的数据上自行调整。通常以默认值为基准向两边适当调整以寻求最佳学习率。
> small/small-ex/base/large: 5e-4 / 5e-4 / 1e-4 / 5e-5

我把你这几个模型套在clue ner任务上，用base测试，学习率也设置e-4级别和 e-5次方级别，评估f1极低 ，num_train_epochs 3个批次以上 f1都是零 ， 
            label   num   right   acc   pre   recall   f1
        address   273   4    0.015   0.111   0.016   0.029
           book   121   0    0.000   0.000   0.000   0.000
        company   279   0    0.000   0.100   0.003   0.005
           game   226   84    0.372   0.265   0.380   0.312
     government   190   0    0.000   0.000   0.000   0.000
          movie   101   0    0.000   0.000   0.000   0.000
           name   352   29    0.082   0.248   0.089   0.131
   organization   206   17    0.083   0.185   0.169   0.176
       position   347   36    0.104   0.614   0.127   0.211
          scene   124   0    0.000   0.000   0.000   0.000
总数 1343 , 完全正确数 58 完全准确率 0.043
平均准确率  平均精确率 平均召回率 平均f1
 0.065          0.152            0.078             0.086


学习率调到2 e-5   num_train_epochs 1  , 然后f1 才50几
