### ISSUE TITLE
请问下这个项目和google electra 项目的区别

### ISSUE THREAD

**Issue by 652994331** [ymcui/Chinese-ELECTRA#62]
您好 ， 关于咱们这个项目和 Google electra 的区别。 我个人理解就是两个不同 一个是我们提供了已有的中文预训练模型， 另一个是词表 我们用的21128 也即是bert中文的那个词表 。假如我们要继续预训练 我们要用 build_dataset.py 用21128词表产生tfrecord 然后进行。 其余的 比如 run_pretraining.py run_finetuning.py 和 configure_finetune configure_pretrain 几个文件都和google那个英文版完全一样的 请问是这样吗。 谢谢

**Comment by ymcui** [comment]
是的，用这个词表就是谷歌原版中文BERT的词表。其余的代码参考谷歌ELECTRA源目录即可。

**Comment by 652994331** [comment]
@ymcui 谢谢 近期 在您这个基础上 用自己的数据继续预训练，使用的init_checkpoint 是中文base， lr 2e-4， 训练步数 100w 左右， 虽然预训练模型的loss 相对 您的中文预训练模型还可以， 但是得到的自己的预训练模型 在下游任务的表现相比您的中文预训练模型却有很大的差距，想问问这里面有没有什么需要特别注意的地方呢

**Comment by ymcui** [comment]
batch size是多少？二次预训练的话，目前看你这个LR有点高。

**Comment by 652994331** [comment]
@ymcui  train batch 是 100, 我的机器是 p40系列的 单卡 base electra 已到极限了。 我昨天发现了问题所在, 是 init_checkpoint的问题, 没有成功读入, 可能导致 train from scratch. 谢谢您
