### ISSUE TITLE
预训练时disc_recall   disc_precision 都是0

### ISSUE THREAD

**Issue by ZJiaBin** [ymcui/Chinese-ELECTRA#66]
这正常吗，没找到是哪里的问题~~

**Comment by ymcui** [comment]
麻烦描述更详细一点。代码用的是谷歌原版的代码吗？从random开始训练的还是二次预训练？
或者可以对比训练前后的模型在下游任务上的效果有何差别。

**Comment by ZJiaBin** [comment]
感谢回复！找到原因啦，是因为lr用的代码里的默认值（5e-4）,调整整1e-4就可以了
