### ISSUE TITLE
关于复现LCQMC任务的一些疑问

### ISSUE THREAD

**Issue by GJHHHH** [ymcui/Chinese-ELECTRA#67]
我根据readme的使用方法进行操作，提示“writing predictions is not supported for this task”，于是我在代码“ if task.name in ["cola", "mrpc", "mnli", "sst", "rte", "qnli", "qqp", "sts"]:”中增加了lcqmc。但是屏幕只输出loss没有Accuracy。请问是哪里出错了？如何复现出readme中所展示的效果？

**Comment by ymcui** [comment]
贴一下shell脚本和json配置？
按你的描述应该是将输出写到某个文件里了，你看一下model所在的目录是不是多出`*_results。txt`文件了。

**Comment by GJHHHH** [comment]
shell脚本:
`!python run_finetuning.py \
    --data-dir . \
    --model-name electra-small \
    --hparams params_lcqmc.json`
json配置:
`{
  "task_names": ["lcqmc"],
  "max_seq_length": 512,
  "vocab_size": 21128,
  "model_size": "small",
  "do_train": false,
  "do_eval": true,
  "write_test_outputs": true,
  "num_train_epochs": 2,
  "learning_rate": 3e-4,
  "train_batch_size": 32,
  "eval_batch_size": 32
}
`
未生成txt文件，仅生成pkl文件
![image](https://user-images.githubusercontent.com/64520634/106152419-61588500-61b8-11eb-9bc9-40c7bdb2e637.png)

**Comment by ymcui** [comment]
关掉`write_test_outputs`试一下。

**Comment by GJHHHH** [comment]
感谢感谢，生成results文件了
