### ISSUE TITLE
请问可以直接使用Paddle Hub或者Hugging Face上的chinese-electra-small模型进行情感分析任务吗？

### ISSUE THREAD

**Issue by jimzeus** [ymcui/Chinese-ELECTRA#68]
感谢分享！
请问下可以直接使用Paddle Hub或者Hugging Face上的chinese-electra-small模型进行情感分析任务吗？我用这两个框架得到的结果都很不稳定，似乎是未经训练的结果。

`
	import paddlehub as hub

	label_map = {0: 'negative', 1: 'positive'}

	model = hub.Module(
	    name='chinese-electra-small',
	    version='2.0.0',
	    task='seq-cls',
	    load_checkpoint='/path/to/parameters',
	    label_map=label_map)
	result = model.predict(data, max_seq_len=500, batch_size=1, use_gpu=False)
`

`
from transformers import pipeline
p = pipeline("sentiment-analysis", "hfl/chinese-electra-small-discriminator")
result = p(data)
`

**Comment by ymcui** [comment]
是需要经过下游任务数据进行训练的，并不能够直接进行情感分类。

**Comment by jimzeus** [comment]
看了下readme，训练是需要结合Electra项目里的脚本完成的吧？

**Comment by jimzeus** [comment]
readme是不是有些问题：
“下载CMRC 2018训练集和开发集，并重命名为train.json和dev.json。 将两个文件放到${data-dir}/models/${task-name}”

这里的models是不是应该改成finetuning_data？

**Comment by ymcui** [comment]
感谢，已经修改了
