### ISSUE TITLE
下游微调任务  CMRC 2018训练集和开发集

### ISSUE THREAD

**Issue by ywm108** [ymcui/Chinese-ELECTRA#7]
按照网站的提示，没有运行成功啊，json格式的数据转换成tfrecord的代码，已经写好了吗？还是需要自己加。是否我只要按照提示格式，放好数据直接运行吗？

**Comment by ymcui** [comment]
已经集成了CMRC 2018的处理脚本，按流程走就可以了。
没有运行成功的话，麻烦贴一下报错内容。

**Comment by ymcui** [comment]
没有新信息，无法提供进一步支持。如有必要请随时reopen。
