### ISSUE TITLE
huggingface.co上chinese-electra-180g-small-discriminator的文件里缺少tokenizer.json

### ISSUE THREAD

**Issue by zihoudanyuan** [ymcui/Chinese-ELECTRA#70]
您好，下载模型及相关文件时（https://huggingface.co/hfl/chinese-electra-180g-small-discriminator/tree/main）未发现tokenizer.json，能否生成然后上传一下。
看google/electra-base-discriminator(https://huggingface.co/google/electra-base-discriminator)是有tokenizer.json的，这个tokenizer.json是不能直接用于chinese-electra-180g-small-discriminator模型吧

**Comment by ymcui** [comment]
有tokenizer_config.json啊

**Comment by ymcui** [comment]
当前版本的transformers库中不叫tokenizer.json，详见：https://huggingface.co/transformers/model_sharing.html#check-the-directory-before-pushing-to-the-model-hub

**Comment by zihoudanyuan** [comment]
看了您给的链接，里面确实没有要求上传tokenizer.json。
补充一下，这里想请教的tokenizer.json是"the fast version of the tokenizer"，可能和tokenizer_config.json不同，类似google/electra-base-discriminator下面的tokenizer.json。
我从huggingface Transformer的tokenization_utils_base.py里看tokenizer.json的注释是“ Fast tokenizers (provided by HuggingFace tokenizer's library) can be saved in a single file”。
在huggingface transformers的 AutoTokenizer.from_pretrained()方法当use_fast参数为True时，会应用到tokenizer.json，我是在无外网的环境使用，想提前缓存下好tokenizer.json。

**Comment by ymcui** [comment]
你试一下官方提供的转换工具吧：https://github.com/huggingface/transformers/blob/master/src/transformers/convert_slow_tokenizers_checkpoints_to_fast.py

后续有空了再传。

**Comment by ymcui** [comment]
已支持，关闭issue。
