### ISSUE TITLE
Huggingface 的 legal base 和 legal small tf版是同一个模型

### ISSUE THREAD

**Issue by OpenWaygate** [ymcui/Chinese-ELECTRA#75]
两个模型的SHA256一样。

![image](https://user-images.githubusercontent.com/27287694/139537993-67719a35-8516-4b40-9f02-ba3e4f7c8352.png)

![image](https://user-images.githubusercontent.com/27287694/139538036-9d56775d-5ecd-441d-ad67-2e8d8f7e85e5.png)

**Comment by ymcui** [comment]
感谢告知，已更新模型和config。
