### ISSUE TITLE
参数中的discriminator_predictions是什么？

### ISSUE THREAD

**Issue by lotress** [ymcui/Chinese-ELECTRA#76]
transformers载入huggingface hub上的chinese-electra-180g-small-discriminator模型时提示discriminator_predictions参数没有使用，请问这些参数用于哪些模块，在什么任务上训练过？非常感谢

**Comment by ymcui** [comment]
https://github.com/ymcui/Chinese-ELECTRA/blob/6a0d45aa1887a7228769166dc9058b6380f98bca/run_pretraining.py#L192

**Comment by lotress** [comment]
OK, thank you.
