### ISSUE TITLE
Bug in preprocessing data?

### ISSUE THREAD

**Issue by mrzrx** [ymcui/Chinese-ELECTRA#77]
![image](https://user-images.githubusercontent.com/32259834/144046266-7e31a33a-a27b-49df-93c6-8d7bc84021c2.png)

**Comment by mrzrx** [comment]
Maybe it should be `len(first_segment)==0` as google_electra?

**Comment by ymcui** [comment]
谷歌的代码在后续有修复，如果重新训练的话就用谷歌repo里的代码吧。
具体修复历史看这个commit: https://github.com/google-research/electra/commit/1ed085288ed265898cdb5deaf55bd56da252af80
