### ISSUE TITLE
应用electra-discriminator训练过的模型作分类任务时部分权重没用上

### ISSUE THREAD

**Issue by TinykWong** [ymcui/Chinese-ELECTRA#84]
我用hfl/chinese-electra-180g-small-discriminator经过训练后想拿来做推理，出现了下面的warning
Some weights of the model checkpoint at hfl/chinese-electra-180g-small-discriminator were not used when initializing ElectraModel: ['discriminator_predictions.dense.weight', 'discriminator_predictions.dense_prediction.bias', 'discriminator_predictions.dense_prediction.weight', 'discriminator_predictions.dense.bias'] 
- This IS expected if you are initializing ElectraModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing 
a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing ElectraModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
-显然我是属于出现了not expected的情况，请问一下这要怎么解决？

**Comment by ymcui** [comment]
你可以下载一下本repo中的tf版模型进行自行转换，看看是否还会出现同样的问题。
