### ISSUE TITLE
huggingface上的hfl/chinese-legal-electra-base-discriminator缺失vocab.txt文件

### ISSUE THREAD

**Issue by JasonCZH4** [ymcui/Chinese-ELECTRA#87]
缺失vocab.txt文件，导致使用`AutoTokenizer.from_pretrained`的时候报错

**Comment by ymcui** [comment]
感谢告知，已更新：https://huggingface.co/hfl/chinese-legal-electra-base-discriminator/tree/main

**Comment by JasonCZH4** [comment]
感谢神速回复，已经可以正常使用了。

**Comment by UACurry** [comment]
> 缺失vocab.txt文件，导致使用`AutoTokenizer.from_pretrained`的时候报错

可以告知一下，可以使用这个模型做法律文书的NER任务吗

**Comment by JasonCZH4** [comment]
> > 缺失vocab.txt文件，导致使用`AutoTokenizer.from_pretrained`的时候报错
> 
> 可以告知一下，可以使用这个模型做法律文书的NER任务吗

electra就是bert的变体，bert能做ner，ELECTRA当然能做
