### ISSUE TITLE
微调后的模型大小问题

### ISSUE THREAD

**Issue by zidong-onepiece1** [ymcui/Chinese-ELECTRA#88]
你好！多有打扰。
微调180g-base模型做文本分类任务，为什么微调后的模型比base模型大小要大很多。模型大小从**400M到了1.1G**。我认为微调时在模型后添加dense层和softmax，并不会导致模型参数量增加这么多，那么到底是什么原因导致的呢？
恳请解答！

**Comment by ymcui** [comment]
合理猜测是因为除了模型本身参数之外还保存了优化器的相关状态（例如Adam的动量等）。
如果你不需要这部分东西（例如不会在这个模型的基础上进一步训练/精调）可以不保存。
TensorFlow代码的话可以把优化器改为SGD再重新加载这个模型，初始化的时候就会保存一个不带这些状态的权重文件。

**Comment by zidong-onepiece1** [comment]
感谢您的解答
