### ISSUE TITLE
finetuning训练没有运行在GPU上

### ISSUE THREAD

**Issue by kelvinleen** [ymcui/Chinese-ELECTRA#9]
CUDA_VISIBLE_DEVICES=1 python run_finetuning.py xxxx
程序没有运行在GPU上，信息如下：

![image](https://user-images.githubusercontent.com/14268422/78650642-cc676100-78f1-11ea-898c-099d35602071.png)

这个是什么原因？

**Comment by Gemini77** [comment]
同问，请问解决了吗
