### ISSUE TITLE
预训练数据文件格式，是一行一个句子，还是一行一个包含多个句子的文档

### ISSUE THREAD

**Issue by hitwangshuai** [ymcui/Chinese-ELECTRA#90]
您好先看了下代码，还有几个疑问问下：
1.预训练数据文件格式，是一行一个句子，还是一行一个包含多个句子的文档
2.预训练任务没有nsp任务了，构建序列时我看还是用了两个segment吗，希望给下解释
3.预训练数据这块我代码中好像没看到有做shuffle，我需要对所有语料文本行做shuffle处理吗

**Comment by ymcui** [comment]
建议你仔细学习一下ELECTRA论文，这个项目的代码基本和原版ELECTRA是一样的。

**Comment by hitwangshuai** [comment]
![image](https://github.com/ymcui/Chinese-ELECTRA/assets/22500910/de009b09-7c5e-40be-a441-cae247d3e783)
你好，辛苦看下这是bug嘛，跟原来electra不一样，感觉这块你们是不是改错了

**Comment by hitwangshuai** [comment]
原始electra的数据处理是这样的：
![image](https://github.com/ymcui/Chinese-ELECTRA/assets/22500910/193f166d-854f-4c43-b7aa-25745566a3a3)

**Comment by ymcui** [comment]
你看一下他们的commit历史，你列举的新脚本是他们后来改过的。如果你要自己训练建议用原版最新脚本。

**Comment by hitwangshuai** [comment]
ok。我打算用你们的模型做热启。你们对原方法没有做啥修改是吗？如果没做啥修改的话，我就拿原脚本训了

**Comment by ymcui** [comment]
是，你load不起来就自己diff一下本项目的代码和最新版的原版electra代码吧。

**Comment by hitwangshuai** [comment]
那是不是你们这个180g版本模型，是拿他们有bug的代码训练的呢？

**Comment by ymcui** [comment]
暂时没空check。你说的bug方面，可能会影响训练效果，但如果你是二次预训练，纠结这个没什么必要，模型结构没有什么变化，权重还是可以继承。如果你担心这个bug会影响你二次预训练，那就暂时不要用了。
